export const allRouteStopsPosition = (state) => state.allRouteStopsPosition;
export const allRouteBusPosition = (state) => state.allRouteBusPosition;
export const busCardList = (state) => state.busCardList;
export const busStopOfRoute = (state) => state.busStopOfRoute;
export const busRouteShapeData = (state) => state.busRouteShapeData;
export const bikeCardList = (state) => state.bikeCardList;
export const currentDistrict = (state) => state.currentDistrict;
export const fareBufferZoneDescriptionZh = (state) => (RouteUID) => {
  const targetBus = state.busCardList.find((bus) => bus.RouteUID === RouteUID);
  if (!targetBus.FareBufferZoneDescriptionZh) return [];
  return targetBus.FareBufferZoneDescriptionZh.split('－');
};
export const goToFirstStop = (state) => state.goToFirstStop;
export const goToUserPosition = (state) => state.goToUserPosition;
export const goBackToMobileSearch = (state) => state.goBackToMobileSearch;
export const isSearching = (state) => state.isSearching;
export const isChangeSideMenuHeight = (state) => state.isChangeSideMenuHeight;
export const isLoading = (state) => state.isLoading;
export const mobileNavSearchType = (state) => state.mobileNavSearchType;
export const desktopNavSearchType = (state) => state.desktopNavSearchType;
export const searchInputValue = (state) => state.searchInputValue;
export const showBusStopDirection = (state) => state.showBusStopDirection;
export const searchType = (state) => state.searchType;
export const userPosition = (state) => state.userPosition;
