export const CLEAR_BUSLIST = 'CLEAR_BUSLIST';
export const CHANGE_SEARCHING_STATUS = 'CHANGE_SEARCHING_STATUS';
export const CHANGE_SIDEMENU_HEIGHT = 'CHANGE_SIDEMENU_HEIGHT';
export const GET_NEARBY_CITY_BUS = 'GET_NEARBY_CITY_BUS';
export const GET_ALL_CITY_BUS = 'GET_ALL_CITY_BUS';
export const GET_CURRENT_DISTRICT = 'GET_CURRENT_DISTRICT';
export const GET_BUS_BY_KEYWORD = 'GET_BUS_BY_KEYWORD';
export const GET_BUS_STOPS_BY_ROUTE = 'GET_BUS_STOPS_BY_ROUTE';